export default {
  document: "MDocument",
  chunk: ".chunk()",
  embeddings: ".embed()",
  "extract-params": "ExtractParams",
  rerank: "rerank()",
  rerankWithScorer: "rerankWithScorer()",
  "metadata-filters": "メタデータフィルタ",
  "database-config": "DatabaseConfig",
  "graph-rag": "GraphRAG",
  astra: "AstraVector",
  chroma: "ChromaVector",
  vectorize: "CloudflareVector",
  pg: "PgVector",
  libsql: "LibSQLVector",
  mongodb: "MongoDBVector",
  couchbase: "CouchbaseVector",
  opensearch: "OpenSearchVector",
  pinecone: "PineconeVector",
  qdrant: "QdrantVector",
  turbopuffer: "TurboPuffer",
  upstash: "UpstashVector",
  lance: "LanceVector",
  s3vectors: "S3Vectors",
};
