const meta = {
  index: "Overview",
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  deepseek: "DeepSeek",
  mistral: "Mistral",
  xai: "xAI",
  alibaba: "Alibaba",
  "alibaba-cn": "Alibaba (China)",
  baseten: "Baseten",
  cerebras: "Cerebras",
  chutes: "Chutes",
  cortecs: "Cortecs",
  deepinfra: "Deep Infra",
  fastrouter: "FastRouter",
  "github-models": "GitHub Models",
  inception: "Inception",
  inference: "Inference",
  llama: "Llama",
  lmstudio: "LMStudio",
  lucidquery: "LucidQuery AI",
  modelscope: "ModelScope",
  moonshotai: "Moonshot AI",
  "moonshotai-cn": "Moonshot AI (China)",
  morph: "Morph",
  nvidia: "Nvidia",
  opencode: "OpenCode Zen",
  perplexity: "Perplexity",
  requesty: "Requesty",
  submodel: "submodel",
  synthetic: "Synthetic",
  upstage: "Upstage",
  venice: "Venice AI",
  wandb: "Weights & Biases",
  zai: "Z.AI",
  "zai-coding-plan": "Z.AI Coding Plan",
  zhipuai: "Zhipu AI",
  "zhipuai-coding-plan": "Zhipu AI Coding Plan",
};

export default meta;
