const meta = {
  "custom-scorer": "Custom Scorer",
  "answer-relevancy": "Answer Relevancy",
  "answer-similarity": "Answer Similarity",
  bias: "Bias",
  completeness: "Completeness",
  "content-similarity": "Content Similarity",
  "context-relevance": "Context Relevance",
  "context-precision": "Context Precision",
  faithfulness: "Faithfulness",
  hallucination: "Hallucination",
  "keyword-coverage": "Keyword Coverage",
  "textual-difference": "Textual Difference",
  "tone-consistency": "Tone Consistency",
  "tool-call-accuracy": "Tool Call Accuracy",
  "prompt-alignment": "Prompt Alignment",
  "noise-sensitivity": "Noise Sensitivity",
  toxicity: "Toxicity",
};
export default meta;
