const meta = {
  "mastra-class": "Mastra",
  getAgent: ".getAgent()",
  getAgents: ".getAgents()",
  getAgentById: ".getAgentById()",
  getWorkflow: ".getWorkflow()",
  getWorkflows: ".getWorkflows()",
  getMemory: ".getMemory()",
  setStorage: ".setStorage()",
  getServer: ".getServer()",
  getMCPServer: ".getMCPServer()",
  getVector: ".getVector()",
  getVectors: ".getVectors()",
  getDeployer: ".getDeployer()",
  getStorage: ".getStorage()",
  getMCPServers: ".getMCPServers()",
  getTelemetry: ".getTelemetry()",
  setTelemetry: ".setTelemetry()",
  getLogs: ".getLogs()",
  getLogsByRunId: ".getLogsByRunId()",
  getLogger: ".getLogger()",
  setLogger: ".setLogger()",
};
export default meta;
